/*
Name to be asigned for anonymous users who post comments, etc. on-site
*/
const userNames = [
    "Star Platinum",
    "Magician's Red",
    "Hermit Purple",
    "Hierophant Green",
    "Silver Chariot",
    "The Fool",
    "The World",
    "Tower of Gray",
    "Dark Blue Moon",
    "Strength",
    "Ebony Devil",
    "Yellow Temperance",
    "Hanged Man",
    "Emperor",
    "Empress",
    "Wheel of Fortune",
    "Justice",
    "Lovers",
    "Sun",
    "Death Thirteen",
    "Judgement",
    "High Priestess",
    "Geb",
    "Khnum",
    "Tohth",
    "Anubis",
    "Bastet",
    "Sethan",
    "Osiris",
    "Horus",
    "Atum",
    "Tenore Sax",
    "Cream",
    "Holy's Stand",
    "Joestar Stand",
    "Crazy Diamond",
    "Star Platinum",
    "The Hand",
    "Echoes",
    "Heaven's Door",
    "Killer Queen",
    "Aqua Necklace",
    "Bad Company",
    "Red Hot Chili Pepper",
    "The Lock",
    "Surface",
    "Love Deluxe",
    "Pearl Jam",
    "Hermit Purple",
    "Achtung Baby",
    "Ratt",
    "Harvest",
    "Cinderella",
    "Atom Heart Father",
    "Boy II Man",
    "Earth Wind and Fire",
    "Highway Star",
    "Stray Cat",
    "Super Fly",
    "Enigma",
    "Cheap Trick",
    "Nijimura's Father's Stand",
    "Gold Experience",
    "Sticky Fingers",
    "Moody Blues",
    "Sex Pistols",
    "Aerosmith",
    "Purple Haze",
    "Spice Girl",
    "Silver Chariot",
    "Chariot Requiem",
    "Gold Experience Requiem",
    "King Crimson",
    "Echoes",
    "Black Sabbath",
    "Soft Machine",
    "Kraft Work",
    "Little Feet",
    "Man in the Mirror",
    "Mr.President",
    "Beach Boy",
    "The Grateful Dead",
    "Baby Face",
    "White Album",
    "Clash",
    "Talking Head",
    "Notorious B.I.G",
    "Metallica",
    "Green Day",
    "Oasis",
    "Rolling Stones",
    "Natural Resources Worker's Stand",
    "Stone Free",
    "Star Platinum:The World",
    "Kiss",
    "Burning Down the House",
    "Foo Fighters",
    "Weather Report",
    "Diver Down",
    "Whitesnake",
    "C-Moon",
    "Made in Heaven",
    "Goo Goo Dolls",
    "Manhattan Transfer",
    "Highway to Hell",
    "Marilyn Manson",
    "Jumpin' Jack Flash",
    "Limp Bizkit",
    "Survivor",
    "Planet Waves",
    "Dragon's Dream",
    "Yo-Yo Ma",
    "Green, Green Grass of Home",
    "Jail House Lock",
    "Bohemian Rhapsody",
    "Sky High",
    "Under World",
    "Boiling Water Stand",
    "Emporio's Mother's Stand",
    "Tusk",
    "Ball Breaker",
    "Oh! Lonesome Me",
    "Scary Monsters",
    "Cream Starter",
    "Ticket to Ride",
    "Dirty Deeds Done Dirt Cheap",
    "In a Silent Way",
    "Hey Ya!",
    "Tomb of the Boom",
    "Boku no Rhythm wo Kiitekure",
    "Wired",
    "Mandom",
    "Catch the Rainbow",
    "Sugar Mountain's Spring",
    "Tatoo You!",
    "Tubular Bells",
    "20th Century Boy",
    "Civil War",
    "Chocolate Disco",
    "THE WORLD",
    "Emerald Searcher's Stand",
    "Soft & Wet",
    "Paisley Park",
    "Nut King Call",
    "Paper Moon King",
    "King Nothing",
    "Speed King",
    "Killer Queen",
    "Fun Fun Fun",
    "California King Bed",
    "Born This Way",
    "Les Feuilles",
    "I Am a Rock",
    "Doobie Wah!",
    "Love Love Deluxe",
    "Schott Key No.1",
    "Schott Key No.2",
    "Vitamin C",
    "Walking Heart",
    "Milagro Man",
    "Blue Hawaii",
    "Doggy Style",
    "Brain Storm",
    "Ozon Baby",
    "Awaking III Leaves",
    "Doctor Wu",
    "Kaato's Stand",
    "Tusk",
    "Dark Mirage",
    "Satanic Coupler",
    "Ptah",
    "The Book",
    "Memory of Jet",
    "The Cure",
    "Public Image Limited",
    "Joy Division",
    "Purple Haze Distortion",
    "Voodoo Child",
    "All Along the Watchtower",
    "Manic Depression",
    "Rainy Day Dream Away",
    "Dolly Dagger",
    "Night Bird Flying",
    "C-Moon Ultimate Requiem",
    "NYPD Blue",
    "U-Boat",
    "The Iron Ladies",
    "Singing in the Rain",
    "Ultimate D4C",
    "Evil Dead",
    "Videodrome",
    "Stepmom",
    "Grand Bleu",
    "The Passion",
    "The World Ultimate",
    "Arrow Cross House",
    "Stray Dog",
    "Twister",
    "Dune",
    "Face Off",
    "Blue Thunder",
    "Whitesnake Ultimate",
    "Made in Heaven Ultimate Requiem",
    "Right Stuff",
    "Rear Window",
    "Blob",
    "Stand User's Stand",
    "Strange Relation",
    "Kaoru's Stand",
    "Love Note",
    "Gucci Bag Stand",
    "Remote Romance",
    "Berry Berry Skull",
    "Assy the Horse",
    "The World Over Heaven",
    "House of Holy",
    "JoJosapiens",
]